"""relate user to photo

Revision ID: 671cbed01ad8
Revises: f17787790e1d
Create Date: 2020-05-27 15:06:18.042721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671cbed01ad8'
down_revision = 'f17787790e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photo', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_column('photo', 'user_id')
    # ### end Alembic commands ###
