"""add file_path value to model

Revision ID: b41879b341ea
Revises: d4e59e0bc4be
Create Date: 2020-05-03 22:07:36.783460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41879b341ea'
down_revision = 'd4e59e0bc4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('file_path', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'file_path')
    # ### end Alembic commands ###
