"""public key on photo model

Revision ID: d4e59e0bc4be
Revises: 71b0699a266a
Create Date: 2020-04-27 07:55:52.949024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e59e0bc4be'
down_revision = '71b0699a266a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'public')
    # ### end Alembic commands ###
